dice loss
fastestimator/fastestimator pull request #1237
Opened 2022-04-06 22:38 UTC by aashokvardhan

2022-04-07 19:03 UTC, vbvg2008 requested changes

2022-04-07 19:03 UTC, vbvg2008 commented on fastestimator/backend/dice_loss.py
> +
cast y_true to be the same type of y_pred

2022-04-07 19:03 UTC, vbvg2008 commented on fastestimator/op/tensorop/loss/dice_loss.py
> +        return dice_loss(y_pred, y_true, self.log_loss, self.soft_dice_loss, self.average_loss, self.channel_average)
apply the 1-dice or log(dice) in this tensorOp

2022-04-07 19:03 UTC, vbvg2008 commented on fastestimator/trace/metric/dice.py
apply the binary thresholding in the trace

2022-04-08 03:08 UTC, aashokvardhan commented on fastestimator/backend/dice_loss.py
> +# Copyright 2022 The FastEstimator Authors. All Rights Reserved.
The file only calculates dice score.

2022-04-08 03:08 UTC, aashokvardhan commented on fastestimator/backend/dice_loss.py
> +            return -np.log(dice)
MOved the logic to dice score.

2022-04-12 19:42 UTC, vbvg2008 requested changes

2022-04-12 19:42 UTC, vbvg2008 commented on fastestimator/backend/dice_score.py
> +    y_true = convert_input_precision(y_true)
converting precision here isn't necessary. 

cast y_true and epsilon to be the same type as y_red

2022-04-12 19:42 UTC, vbvg2008 commented on fastestimator/backend/__init__.py
> +from fastestimator.backend.convert_tensor_precision import convert_input_precision
avoid renaming import function

2022-04-12 19:42 UTC, vbvg2008 commented on fastestimator/backend/dice_score.py
> +            return tf.square(y_true) + tf.square(y_pred)
**2

2022-04-12 19:42 UTC, vbvg2008 commented on fastestimator/backend/dice_score.py
> +        dice_score = reduce_mean(dice_score, axis=1)
need to extend the dice to Nd, by assuming tf:[B, ..., C], torch:[B,C, ...]

2022-04-12 19:42 UTC, vbvg2008 commented on fastestimator/op/tensorop/dice.py
> +            y_pred: Prediction with a shape like (Batch, C). dtype: float32 or float16.
Docstring

2022-04-12 19:42 UTC, vbvg2008 commented on fastestimator/trace/metric/dice.py
> +        y_pred = convert_input_precision(y_pred > self.threshold)
conversion is unnecessary

2022-04-15 17:58 UTC, vbvg2008 requested changes
just 2 minor comments

2022-04-15 17:58 UTC, vbvg2008 commented on fastestimator/op/tensorop/dice.py
> +class DiceScore(TensorOp):
let's call it Dice

2022-04-15 17:58 UTC, vbvg2008 commented on fastestimator/op/tensorop/dice.py
> +        return -dice
let's have an argument `negate` with default False. 

When negate is False, we will return dice, when True, we will return -dice

2022-04-18 16:29 UTC, vbvg2008 approved these changes
LG

2022-04-18 16:29 UTC, merged